"""Property-based tests for ``ralph_loop.persona_registry.PersonaRegistry`` (design Property 5).

These tests exercise Property 5 from ``design.md``:

    For any directory D containing n persona files, PersonaRegistry.load(D)
    either (a) returns a dict[str, Persona] whose keys are exactly the
    ``name`` fields in the files and whose values contain the parsed
    description, prompt template, and optional fields, when every file
    has the required fields and no two files share a ``name``; or
    (b) fails fast with a non-zero exit when any file is missing a
    required field (identifying the file and field) or two files declare
    the same ``name`` (identifying the conflict).

The test is split across three complementary properties, each driving
one branch of the loader:

- The happy-path property writes a list of persona dicts with unique
  ``name`` fields and asserts the registry mirrors them exactly.
- The duplicate-name property writes a list containing at least one
  repeated ``name`` and asserts the loader raises
  ``PersonaRegistryError`` naming the duplicated value.
- The missing-required-field property writes a well-formed dict with
  one required field removed and asserts the loader raises
  ``PersonaRegistryError`` naming the file and the missing field.

Filesystem materialization uses ``tempfile.TemporaryDirectory`` inside
each hypothesis example so the generated data is written to a fresh
directory on every draw and torn down afterwards.

Requirements validated: 3.2, 3.4, 3.5, 3.6, 3.8.
"""

# Feature: ralph-loop, Property 5: Persona registry loader is a deterministic mapping with fail-fast duplicates and missing fields

from __future__ import annotations

import tempfile
from pathlib import Path
from typing import Any

import pytest
import yaml
from hypothesis import given
from hypothesis import strategies as st

from ralph_loop.models import Persona
from ralph_loop.persona_registry import PersonaRegistry, PersonaRegistryError

from tests.strategies import (
    persona_dict_list_unique_strategy,
    persona_dict_list_with_duplicate_strategy,
    persona_dict_strategy,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _write_persona_yaml(directory: Path, filename: str, data: dict[str, Any]) -> Path:
    """Serialize ``data`` as YAML into ``directory/filename`` and return the path.

    ``yaml.safe_dump`` produces a deterministic mapping with block-style
    scalars for multiline strings. All string values generated by
    ``persona_text_strategy`` / ``persona_name_strategy`` use a
    YAML-safe alphabet, so serialization never needs special escaping.
    """
    path = directory / filename
    # ``sort_keys=False`` keeps the key order predictable for debugging;
    # the loader does not care about key order.
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Happy path (R3.2, R3.4, R3.8)
# ---------------------------------------------------------------------------


@given(persona_dicts=persona_dict_list_unique_strategy(min_size=1, max_size=5))
def test_happy_path_registry_mirrors_input_dicts(
    persona_dicts: list[dict[str, Any]],
) -> None:
    """Validates: Requirements 3.2, 3.4, 3.8.

    When every persona file is well-formed and every ``name`` is
    unique, the loader returns a registry whose:

    - ``all()`` yields a persona per input dict,
    - set of names equals the set of ``name`` fields in the inputs,
    - ``get(name)`` returns the persona whose scalar fields equal the
      corresponding input values.

    This is the deterministic-mapping half of Property 5.
    """
    with tempfile.TemporaryDirectory() as td:
        directory = Path(td)
        # Write one file per dict. Filenames are derived from the index
        # rather than the name so tests don't have to worry about
        # filesystem-unsafe characters; the loader keys by the parsed
        # ``name`` field, not the filename.
        for i, data in enumerate(persona_dicts):
            _write_persona_yaml(directory, f"p{i}.yaml", data)

        registry = PersonaRegistry.load(directory)

        loaded_personas = registry.all()
        assert len(loaded_personas) == len(persona_dicts)

        # Key-set equality: every input ``name`` appears in the registry
        # and nothing extra is present.
        expected_names = {d["name"] for d in persona_dicts}
        actual_names = {p.name for p in loaded_personas}
        assert actual_names == expected_names

        # Value round-trip: every input dict's scalar fields survive the
        # YAML serialize + parse + validate round trip unchanged.
        by_name_input = {d["name"]: d for d in persona_dicts}
        for loaded in loaded_personas:
            expected = by_name_input[loaded.name]
            assert isinstance(loaded, Persona)
            assert loaded.description == expected["description"]
            assert loaded.prompt_template == expected["prompt_template"]
            assert loaded.instructions == expected.get("instructions")
            assert (
                loaded.default_persona_review_pass_condition
                == expected.get("default_persona_review_pass_condition")
            )

            # ``get`` must return the same instance as iterating via
            # ``all`` (same model value).
            got = registry.get(loaded.name)
            assert got is not None
            assert got == loaded


# ---------------------------------------------------------------------------
# Fail-fast: duplicate names (R3.5)
# ---------------------------------------------------------------------------


@given(persona_dicts=persona_dict_list_with_duplicate_strategy())
def test_duplicate_names_raise_persona_registry_error(
    persona_dicts: list[dict[str, Any]],
) -> None:
    """Validates: Requirements 3.5.

    When two or more persona files declare the same ``name``, the
    loader raises :class:`PersonaRegistryError`. The error message
    must contain at least one name that appears in more than one file
    so operators can locate the conflict without reading every
    persona file.

    This is the duplicate-name half of Property 5's fail-fast branch.
    """
    with tempfile.TemporaryDirectory() as td:
        directory = Path(td)
        for i, data in enumerate(persona_dicts):
            _write_persona_yaml(directory, f"p{i}.yaml", data)

        with pytest.raises(PersonaRegistryError) as excinfo:
            PersonaRegistry.load(directory)

        # Identify every name that appears more than once in the input
        # list. The error message must mention at least one of them,
        # since the loader reports the conflict as soon as it sees a
        # second occurrence.
        seen: set[str] = set()
        duplicated: set[str] = set()
        for d in persona_dicts:
            name = d["name"]
            if name in seen:
                duplicated.add(name)
            else:
                seen.add(name)
        assert duplicated, (
            "generator invariant: persona_dict_list_with_duplicate_strategy "
            "must produce at least one duplicated name"
        )

        msg = str(excinfo.value)
        assert any(name in msg for name in duplicated)


# ---------------------------------------------------------------------------
# Fail-fast: missing required fields (R3.6)
# ---------------------------------------------------------------------------


@given(
    data=persona_dict_strategy(
        include_instructions=False,
        include_default_pass=False,
    ),
    missing_field=st.sampled_from(("name", "description", "prompt_template")),
)
def test_missing_required_field_raises_persona_registry_error(
    data: dict[str, Any],
    missing_field: str,
) -> None:
    """Validates: Requirements 3.6.

    When a persona file is missing one of the required fields
    (``name``, ``description``, ``prompt_template``), the loader
    raises :class:`PersonaRegistryError` and the message identifies
    the offending file and field so operators can fix the definition.

    This is the missing-required-field half of Property 5's fail-fast
    branch. ``missing_field`` is drawn via ``st.sampled_from`` so the
    shrinker can converge quickly on the minimal (field, dict) pair
    that triggers the error.
    """
    # Drop the chosen required field from the otherwise-valid dict.
    broken = {k: v for k, v in data.items() if k != missing_field}

    with tempfile.TemporaryDirectory() as td:
        directory = Path(td)
        path = _write_persona_yaml(directory, "broken.yaml", broken)

        with pytest.raises(PersonaRegistryError) as excinfo:
            PersonaRegistry.load(directory)

        msg = str(excinfo.value)
        assert str(path) in msg
        assert missing_field in msg
